FROM golang:1.24-alpine

WORKDIR /app

# Install dependencies
RUN apk add --no-cache tzdata git

# Install Air for live reloading in development
RUN go install github.com/air-verse/air@latest

# The source code will be mounted as a volume from the host
# We don't need to copy anything here since docker-compose mounts ./backend:/app

# Command to run
CMD ["air", "-c", ".air.toml"]