apiVersion: 1

datasources:
  - name: GardenDB
    type: postgres
    uid: garden_postgres
    url: db:5432
    user: ${GF_DATABASE_USER}
    secureJsonData:
      password: ${GF_DATABASE_PASSWORD}
    jsonData:
      database: ${GF_DATABASE_NAME}
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    editable: false
